# Config translated from Karpathy's original nanoGPT implementation

general:
  project_name: 'train_gpt2'
  run_name: '_time:' # default run name is timestamp
  run_description: null
  out_dir: '$OUT_DIR/$project_name/$run_name'
  device_type: 'cuda'            # auto select if blank or cpu, cuda
  distributed_backend: 'nccl'       # nccl, gloo, mpi, horovod)
  distributed_init_method: 'env://' # for horovod, use 'tcp://localhost:23456'
  torch_compile: true # will not compile if Python > 3.11, torch < 2.1.0 or Windows
  seed: 42
  dtype: 'bfloat16'         # float32, float16, bfloat16
  enable_distributed: null # automatically set to true if RANK is set

_env: # creates env vars
  project_name: '_copy: /general/project_name'
  run_name: '_copy: /general/run_name'

logging:
  project_name: '_copy: /general/project_name'
  run_name: '_copy: /general/run_name'
  log_dir: '_copy: /general/out_dir'
  run_description: '_copy: /general/run_description'
  enable_wandb: true
  log_filename: 'log.txt'
  summaries_filename: 'summaries.txt'
  allow_overwrite_log: true
  metrics_type: 'classification'
  summaries_stdout: true

model:
  module: 'nanugpt.models.nanogpt.get_model'
  module_kwargs:
    n_layer: 12
    n_embd: 768
    n_head: 12
    context_length: 1024

tokenizer:
  module: 'nanugpt.tokenizers.tiktoken_wrap.get_tokenizer_factory'
  module_kwargs:
    encoding_name: 'gpt2'

loss:
  module: 'nanugpt.losses.autoregressive_loss.get_loss'

data:
  module: 'nanugpt.data.tokenized_data.get_data'
  module_kwargs:
    dtype: 'uint16'
    device_batch_size: '_copy: /training/device_batch_size'
    eval_batch_size: 32 # 2^15=32768
    data_loader_seed: 8
    context_length: '_copy: /model/module_kwargs/context_length'
    tokenized_train_path: '$DATA_ROOT/tokenized/openwebtext/tiktoken/train.bin'
    tokenized_val_path: '$DATA_ROOT/tokenized/openwebtext/tiktoken/validation.bin'
    tokenized_test_path: null

training:
  device_batch_size: 12
  max_steps: 600000    # for OpenWebText/9B tokens
  enable_train_log: true
  log_every: 20
  grad_clip: 1.0 # disabled if 0.0
  global_batch_size: 480

optimizer:
  module: 'nanugpt.optimizers.adamw_nanogpt.get_optim'
  module_kwargs:
    learning_rate: 6.0E-4
    weight_decay: 0.1
    beta1: 0.9
    beta2: 0.95
    eps: 1.0E-8 # pytorch default

scheduler:
  module: 'nanugpt.schedulers.cosine.get_scheduler'
  module_kwargs:
    warmup_iters: 2000
    max_iters: '_copy: /training/max_steps'
    end_factor: 1.0E-1

generate:
  checkpoint_path: '$OUT_DIR/$project_name'
  checkpoint_name: null # filename or use last from checkpoint_log.yaml, also can be set 'checkpoint_best.pt'

eval:
  eval_every: 1000
  eval_iters: 200 # number of samples to evaluate for dataset
  save_checkpoint: true
  checkoint_after: 0 # starts saving checkpoint after these steps
  checkpoint_every_hr: 2 # take checkpoint every this hours
  checkpoint_keep_best: false # keep only the best checkpoint, otherwise keep all with  _{step}.pt

